local key_maps = {
	{key = "<C-LeftMouse>", func = "definition()"},
	{key = "<Leader>gi", func = "incoming_calls()"},
	{key = "<Leader>go", func = "outgoing_calls()"},
	{key = "<Leader>k", func = "require('navigator.dochighlight').hi_symbol()"},
	{key = "<Leader>re", func = "rename()"},
	{key = "<c-]>", func = "definition()"},
	{key = "GT", func = "require('navigator.treesitter').bufs_ts()"},
	{key = "K", func = "hover({ popup_opts = { border = single }})"},
	{key = "[d", func = "diagnostic.goto_next({ popup_opts = { border = single }})"},
	{key = "[r", func = "require('navigator.treesitter').goto_previous_usage()"},
	{key = "]d", func = "diagnostic.goto_next({ popup_opts = { border = single }})"},
	{key = "]r", func = "require('navigator.treesitter').goto_next_usage()"},
	{key = "g0", func = "document_symbol()"},
	{key = "g<LeftMouse>", func = "implementation()"},
	{key = "gD", func = "declaration({ popup_opts = { border = 'single' }})"},
	{key = "gG", func = "require('navigator.diagnostics').show_diagnostic()"},
	{key = "gL", func = "diagnostic.show_line_diagnostics({ popup_opts = { border = single }})"},
	{key = "gT", func = "require('navigator.treesitter').buf_ts()"},
	{key = "gW", func = "workspace_symbol()"},
	{key = "ga", mode = "n", func = "code_action()"},
	{key = "ga", mode = "v", func = "range_code_action()"},
	{key = "gi", func = "implementation()"},
	{key = "gp", func = "require('navigator.definition').definition_preview()"},
	{key = "gr", func = "references()"},
	{key = "gs", func = "signature_help()"},
	{key = "gt", func = "type_definition()"},
	{mode = "i", key = "<M-k>", func = "signature_help()"},
}
